### ISSUE TITLE
Ports closed?

### ISSUE THREAD

**Issue by chillaaar** [proxidize/proxidize-android#2]
I'm trying to use some specific ports, but they seem to be closed. Is this because the tunnel server does not allow any custom ports?

**Comment by abedlez** [comment]
How are you trying to use the specific port?

**Comment by chillaaar** [comment]
Hi,

I have a browser extension that needs to connect to one of my servers via
that port. It keeps saying that the proxy is blocking it.


--
Best Regards,
Jens Juul

**Comment by abedlez** [comment]
Are you trying to connect to a port that's not the assigned HTTP port? If so, that's not gonna work. The server will only listed to the assigned port.

Why are you trying to use a specific port? This can be implemented by hard coding your desired port in `app/src/main/java/com/legacy/android/ProxyServer.kt` but there's no benefit since these are response connections from the perspective of the proxy server/phone.

**Comment by chillaaar** [comment]
Hi again,

We have previously tried sending the data via a restful API http method and
it was unfortunately unstable and not so fast.

The extension connects to the server via socket port 52000 and then the
extension uses the data it receives to navigate on a website.

If we hard code a desired port, wouldn't we close down all http traffic?


--
Best Regards,
Jens Juul

**Comment by abedlez** [comment]
Take a look at the architecture diagram to understand how this app works.
