### ISSUE TITLE
Proxidize consomme mobile data  quickly

### ISSUE THREAD

**Issue by youssefmougja** [proxidize/proxidize-android#3]
Hi, why does Proxidize consume 10Gb mobile data.
How to solve this problem.
Can i use wifi and 4g together ?

**Comment by AbedElez** [comment]
Q: Why did I use 10 GB of mobile data while using Proxidize Android Legacy.

A: Because you've consumed 5 GB of web data which doubles since incoming & outgoing connections are passing through the same route.

**> Can i use wifi and 4g together ?**

It's planned to finish WiFi backend. But it's not a solution. Use Proxidize MPM if data consumption is important.

And make sure to read the readme to better understand how this app works.
